//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Complaint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complaint()
        {
            this.LabAsigns = new HashSet<LabAsign>();
            this.LabAsigns1 = new HashSet<LabAsign>();
        }
    
        public int Cmplnt_Id { get; set; }
        [Display(Name = "Customer ID")]
        public Nullable<int> Cmplnt_CustId { get; set; }

        [Display(Name = "Organization ID")]
        public Nullable<int> Cmplnt_orgId { get; set; }
        [Display(Name = "Complaint")]
        public string Complnt_content { get; set; }

        [Display(Name = "Status")]
        public Nullable<int> Status { get; set; }
        public string Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Customer Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabAsign> LabAsigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabAsign> LabAsigns1 { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
