//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabAsign
    {
        public int LbAs_id { get; set; }
        public Nullable<int> LbAs_orgId { get; set; }
        public Nullable<int> LbAs_LabId { get; set; }
        public Nullable<int> LbAs_CmplntId { get; set; }
        public Nullable<int> LbAs_complStatus { get; set; }
        public string Date { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        public virtual Complaint Complaint1 { get; set; }
        public virtual Status Status { get; set; }
        public virtual Labor Labor { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Labor Labor1 { get; set; }
        public virtual Organization Organization1 { get; set; }
    }
}
