//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Labor()
        {
            this.LabAsigns = new HashSet<LabAsign>();
            this.LabAsigns1 = new HashSet<LabAsign>();
            this.payrollLabs = new HashSet<payrollLab>();
            this.payrollLabs1 = new HashSet<payrollLab>();
        }
    
        public int Lab_id { get; set; }
        public string Lab_name { get; set; }
        public Nullable<int> Lab_OrgId { get; set; }
        public string Ph_no { get; set; }
        public string address { get; set; }
        public string LastName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabAsign> LabAsigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabAsign> LabAsigns1 { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payrollLab> payrollLabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payrollLab> payrollLabs1 { get; set; }
    }
}
