//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollCust
    {
        public int prCust_id { get; set; }
        public Nullable<int> prCust_OrgId { get; set; }
        public Nullable<int> prCust_CustId { get; set; }
        public Nullable<double> prCust_paymnt { get; set; }
        public string prCust_date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
