//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Rat_Id { get; set; }
        public Nullable<int> Rat_CustId { get; set; }
        public Nullable<int> Rat_orgId { get; set; }
        public Nullable<int> Rat_value { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Rating_Values Rating_Values { get; set; }
    }
}
